### ISSUE TITLE
movo_network_config.bash mentions aliases that do not always exists

### ISSUE THREAD

**Issue by nightingale-project** [nightingale-project/kinova-movo#21]
movo_network_config.bash mentions the movo1 and movo2 aliases. these aliases do not exist when not connected to the robohub DNS. if the robot is on the 3rd floor and we source the ws, we get an error bc those aliases are not defined. we should fix this

**Comment by nightingale-project** [comment]
@alexswerner how do u suggest we resolve this? should we hardcode the br0 interface ip addr or the enp addr?
![image](https://user-images.githubusercontent.com/109867490/204395050-35f1cacf-156a-4b7e-8d3f-cdace84f9f4b.png)

![image](https://user-images.githubusercontent.com/109867490/204395153-97d55d8a-0286-416e-a1a9-fc38c61e3932.png)

**Comment by alexswerner** [comment]
I'm not sure if I'm following here. The br0 IP address should be set when the interfaces is set up. But please describe the issue you are seeing.

**Comment by younesr1** [comment]
will produced steps to replicate when im back on campus
