### ISSUE TITLE
disable LSM

### ISSUE THREAD

**Issue by younesr1** [nightingale-project/kinova-movo#26]
I think we should disable [LSM](http://wiki.ros.org/laser_scan_matcher). I think it adds another chunk of complexity we need to spend time understanding and debugging. We also have seen those sus warning msgs about some timing stuff (i dont remember much more). We can talk about adding this in later once things are most stable and we are looking to improve things.

We should simplify the system until we get something working reliably.

**Comment by younesr1** [comment]
movo_common/movo_config/movo_config.bash line 18 and 24 should be false

**Comment by younesr1** [comment]
Here's how Kinova "fuses" LSM and WO to produce the /movo/odometry/local_filtered topic:
The pose part of the odom msg comes strictly from the LSM
The twist part of the odom msg comes strictly from the WO

Furthermore, when LSM is enabled, the TF from odom to baselink comes strictly from LSM. 

This behavior is surprising. Kinova does not seem to trust WO at all when LSM is used. @brandonjdehart isnt WO more reliable than LSM generally? If not perhaps it will be for our use case? Perhaps theyre doing this bc the wheel encoders on the stanley platform are especially bad or something? I think our area in E5 has nice smooth floors so minimal slipping.

**Comment by FelixKHWong** [comment]
LSM - Laser scan matching
WO - Wheel Odometry

**Comment by FelixKHWong** [comment]
Is laser scan matching like AMCL or something else? Would the only issue with just using wheel odometry be that the error can accumulate over time?

**Comment by younesr1** [comment]
> Is laser scan matching like AMCL or something else? Would the only issue with just using wheel odometry be that the error can accumulate over time?

i think theyre 2 different things. amcl is a particle filter. amcl tells u ur pose in the map frame. see the hyper link at the top about LSM. it just tells u  ur pose in the odom frame. i think LSM also suffers from accumulated error but couldnt find anything definititve

**Comment by FelixKHWong** [comment]
To me it seems like AMCL and LSM are super similar. Since LSM is causing issue and AMCL seems to work well for navigation could we just use AMCL for pose estimation instead? Then just as you suggested we can put in LSM later if we need it?

**Comment by brandonjdehart** [comment]
You will always get better results by effectively combining sensor readings from multiple sources, as the drawbacks of a given sensor can generally be made up for by the benefits of another one. If you have a way to do decent sensor fusion, then combining LSM and WO (and any other reliable sources you've got) is always going to get you better results than one or the other on its own. The only time this isn't the case is when sensor readings are extremely terrible, which might be the case for wheel-only odometry for a meccanum wheel base like the Movo.

**Comment by younesr1** [comment]
Edit to my statements above about how Kinova does WO. Kinova does not completely discard the positional estimate from the wheel encoders. the LSM pkg uses the positional reading from WO as an inital seed in their search for the change in pose based on laser scans.

Dr. DeHart: That's a good point. I did not know meccanum wheels were prone to slippage. I'll close this. We'll can reconsider this in the future if start seeing unexplained poor system performance. So far, all the poor performance we've seen with nav has other explanations

**Comment by younesr1** [comment]
When tuning nav for the e5 hallway, it was observed that LSM reports several warnings about failing to match scans. this might be due to the feature-poor nature of the hallways. anyway, LSM has been disabled in this PR https://github.com/nightingale-project/kinova-movo/pull/36
